services:
  kafka:
    image: apache/kafka:latest
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    networks:
      - pipline-network
    healthcheck:
      test: ["CMD", "bash", "-c", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5

  traefik:
    image: traefik:v2.9
    container_name: traefik_lb
    command:
      - "--api.insecure=true"
      # - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--entrypoints.web.address=:8081"
      - "--entrypoints.traefik.address=:8080"
    ports:
      - "8081:8081"  # API Gateway für Microservices
      - "8080:8080"  # Traefik Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - pipline-network

  cryptography-service:
    build:
      context: .
      dockerfile: Dockerfile.crypto
    container_name: cryptography_service
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cryptography.rule=Host(`localhost`)"
      - "traefik.http.services.cryptography.loadbalancer.server.port=8000"
    networks:
      - pipline-network

  factory-service:
    build:
      context: .
      dockerfile: Dockerfile.factory
    container_name: factory_service
    depends_on:
      - cryptography-service
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.factory.rule=PathPrefix(`/stream`)"
      - "traefik.http.services.factory.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.sse.headers.customResponseHeaders.Connection=keep-alive"
      - "traefik.http.middlewares.sse.headers.customResponseHeaders.Cache-Control=no-cache"
      - "traefik.http.routers.factory.middlewares=sse"
    networks:
      - pipline-network

  verification-service:
    build:
      context: .
      dockerfile: Dockerfile.verification
    container_name: verification_service
    depends_on:
      cryptography-service:
        condition: service_started
      factory-service:
        condition: service_started
      kafka:
        condition: service_healthy
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.validator.rule=Host(`localhost`)"
      - "traefik.http.services.validator.loadbalancer.server.port=8081"
    networks:
      - pipline-network


networks:
  pipline-network:
    driver: bridge
