services:
  traefik:
    image: traefik:v2.9
    container_name: traefik_lb
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8081"
      - "--entrypoints.traefik.address=:8080"
    ports:
      - "8081:8081"  # API Gateway für Microservices
      - "8080:8080"  # Traefik Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - pipline-network

  cryptography-service:
    build:
      context: .
      dockerfile: Dockerfile.crypto
    container_name: cryptography_service
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cryptography.rule=Host(`localhost`)"
      - "traefik.http.services.cryptography.loadbalancer.server.port=8000"
    networks:
      - pipline-network

  factory-service:
    build:
      context: .
      dockerfile: Dockerfile.factory
    container_name: factory_service
    depends_on:
      - cryptography-service
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.factory.rule=PathPrefix(`/stream`)"
      - "traefik.http.services.factory.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.sse.headers.customResponseHeaders.Connection=keep-alive"
      - "traefik.http.middlewares.sse.headers.customResponseHeaders.Cache-Control=no-cache"
      - "traefik.http.routers.factory.middlewares=sse"
    networks:
      - pipline-network

  verification-service:
    build:
      context: .
      dockerfile: Dockerfile.verification
    container_name: verification_service
    depends_on:
      - cryptography-service
      - factory-service
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.validator.rule=Host(`localhost`)"
      - "traefik.http.services.validator.loadbalancer.server.port=8081"
    networks:
      - pipline-network

networks:
  pipline-network:
    driver: bridge
